### ISSUE TITLE
Algorithm for Character to Number Conversion 

### ISSUE THREAD

**Issue by hakrsekar** [bhagavad-gita/iproject#10]

**Comment by hakrsekar** [comment]
I am working on this.

**Comment by dvenkatesan1968** [comment]
hi sekar,
pls create a proper website for your company...

http://srila.in/

On Sun, Feb 15, 2015 at 6:13 PM, Sekar Chenniyappan <
notifications@github.com> wrote:

> I am working on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bhagavad-gita/iproject/issues/10#issuecomment-74415948>
> .
>



-- 
Prof.D.Venkatesan
HOD, Department of IT/CSE
BIT Campus,
Anna University - Regional Centre
Tiruchirapalli - 620024
Mobile: 09150903401, 09976906268
Land: 0431- 2407990

**Comment by hakrsekar** [comment]
@dvenkatesan1968 Ya sure sir...

**Comment by hakrsekar** [comment]
Wrote code for this..Output verified.
Now closing this issue...
